### PR TITLE
SFM-437: Removed experiments

### PR DESCRIPTION
**Pull request by ddold**
Removed experiments from the impression invoker. 
There is no analytics implemented in this SDK but when they will be done there will be no experiment to send!

### CODE REVIEW

**Comment by AsafRollout** [comment]
please open a separate SDK5 branch

**Review by apg84 — APPROVED** [review]

**Comment by AsafRollout** [comment]
it's not critical, but we don't need clientExperiment anymore it seems (think it's a experiment converted to a client friendly object)
can just use the original experiment if it's not too hard

**Comment by ddold** [comment]
@AsafRollout we need it for the `targeting`
https://github.com/rollout/rox-go/pull/29/files#diff-2d5032200b4e1dee16f49af449bc2ca9b0f6dae1808b325777bc82aad81c4d8dR96

**Comment by AsafRollout** [comment]
we need to know if there's an experiment, you can keep on the variant the original experiment
we already have a original experiment object, no need to covert it to a client experiment object
it was done to save the covert in each impression call i guess, but now, it's just more redundant object converting

**Pull request merged**
