### PR TITLE
E2e tests

### PR DESCRIPTION
**Pull request by andy-a-o**

### CODE REVIEW

**Review by AsafRollout — COMMENTED** [review]
@andy-a-o 
1. do we need the driver/driver binary?
2. will this build the SDK as well? if this will happen on a PR, and will use the github.com/rollout/rox-go won't it test the latest version, and not the one in the PR?

**Comment by andy-a-o** [comment]
@AsafRollout binary not needed. it should be removed. if not I will check

and yes it must be running the SDK version from the master branch, I will update it.

**Comment by AsafRollout** [comment]
`it must be running the SDK version from the master branch`
do you mean it's a limitation? we do want to run the code with the current branch, before the PR is merged...
i thought Go added an option to get a specific branch...

**Comment by andy-a-o** [comment]
@AsafRollout should be done now. But still to check it I need to merge it. So can we merge please and then continue. It's still not tested yet.

**Review by AsafRollout — APPROVED** [review]
go ahead and merge, we can do fixes in another PR if needed
(i think the server will be missing the "github.com/rollout/rox-go/..." imports, not sure if the run_server should local install the current SDK to use, or how it should be done 🤷 )

**Pull request merged**
